version: "3"

services:
  version: '3'
services:
  mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: animals
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  api:
    build:
      context: .
    ports:
      - "8080:8080"

      