spring:
  api-docs:
    path: /api-docs

  datasource:
    url: jdbc:mysql://localhost:3306/animals
    username: ${PROD-ANIMALS-DB-USERNAME}
    password: ${PROD-ANIMALS-DB-PASSWORD}

  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml