springdoc:
  api-docs:
    path: /api-docs
animal:
  types:
    MAMMALS: ["dog"]
    BIRD: ["owl", "parrot"]
    INVERTEBRATE: ["spider"]
    FISH: ["tuna", "salmon"]
    AMPHIBIAN: ["frog"]
    REPTILES: ["iguana"]

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
