CREATE TABLE IF NOT EXISTS Birds (
  ID VARCHAR(16) NOT NULL PRIMARY KEY,
  birdName VARCHAR(40) NOT NULL
  birdDesc VARCHAR(250) NOT NULL
);


CREATE TABLE IF NOT EXISTS Cats (
  ID VARCHAR(16) NOT NULL PRIMARY KEY,
  catName VARCHAR(40) NOT NULL
  catDesc VARCHAR(250) NOT NULL
);

