CREATE TABLE IF NOT EXISTS animal_tbl
(
    ID BIGINT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_DATE  TIMESTAMP    NOT NULL DEFAULT now(),
    UPDATED_DATE  TIMESTAMP    NOT NULL DEFAULT now(),
    NAME        VARCHAR(50)   NOT NULL,
    DESCRIPTION  VARCHAR(100)  NOT NULL,
    GROUP_NAME      VARCHAR(50)   NOT NULL,
    ANIMAL_TYPE      VARCHAR(50)   NOT NULL
);